# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-svc
# spec:
#   type: LoadBalancer
#   selector:
#     app.kubernetes.io/name: argocd-nginx
#   ports:
#   - port: 80
#     targetPort: 80
